import {
  Thermometer,
  Droplets,
  Sun,
  Volume2,
  Wind,
  Ruler,
  Activity,
  LayoutDashboard,
  History,
  Sparkles,
  Settings,
  Minus,
  Square,
  X,
  Check,
  Send,
  UserCheck,
  UserX,
  CheckCircle2,
  AlertTriangle,
  Loader2,
  Calendar,
  Wifi,
  WifiOff,
  KeyRound,
  Bot,
  RefreshCw,
  ChevronDown,
  Cpu,
  Palette,
  Moon,
  Power,
  Eye,
  EyeOff,
} from 'lucide-react'

const MAP = {
  thermometer: Thermometer,
  droplets: Droplets,
  sun: Sun,
  'volume-2': Volume2,
  wind: Wind,
  ruler: Ruler,
  activity: Activity,
  dashboard: LayoutDashboard,
  history: History,
  sparkles: Sparkles,
  settings: Settings,
  minus: Minus,
  square: Square,
  x: X,
  'check-mark': Check,
  send: Send,
  'user-check': UserCheck,
  'user-x': UserX,
  check: CheckCircle2,
  alert: AlertTriangle,
  loader: Loader2,
  calendar: Calendar,
  wifi: Wifi,
  'wifi-off': WifiOff,
  key: KeyRound,
  bot: Bot,
  refresh: RefreshCw,
  'chevron-down': ChevronDown,
  cpu: Cpu,
  palette: Palette,
  moon: Moon,
  power: Power,
  eye: Eye,
  'eye-off': EyeOff,
}

export default function Icon({ name, className = '', ...props }) {
  const Cmp = MAP[name] || Activity
  return <Cmp className={className} strokeWidth={1.75} {...props} />
}
